[build]
builder = "nixpacks"
buildCommand = "npm install && DISABLE_MEDUSA_ADMIN=true npm run build"

[deploy]
startCommand = "npx medusa db:migrate && node .medusa/server/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
